name: sabanzuri
description: A new Flutter project.

publish_to: 'none'

#version: 1.0.4+1
version: 1.0.3+3 # for InfinitiLottoICE

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  velocity_x: ^4.1.0
  cached_network_image: ^3.2.0
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  shared_preferences: ^2.0.13
  package_info_plus: ^3.0.0
  another_flushbar: ^1.10.28
  fk_user_agent: ^2.1.0
  crypto: ^3.0.1
  flutter_local_notifications: ^9.4.0
  webview_flutter: ^3.0.4
  flutter_downloader: 1.7.1
  image_picker: ^0.8.5
  lottie: ^1.2.1
  flutter_staggered_animations: ^1.0.0
  dotted_border: ^2.0.0+3
  flutter_switch: ^0.3.2
  flutter_social_content_share: ^1.0.2
  flutter_share_me: ^0.11.0
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.1.7
  share_plus: ^6.3.0
  flutter_svg: ^1.1.6
  gradient_widgets: ^0.6.0
  flutter_localization: ^0.1.12
  audioplayers: ^5.1.0
  scan: ^1.6.0
  mobile_scanner: ^3.3.0
  qr_code_scanner: ^1.0.1
  permission_handler: ^10.4.3
  uni_links: ^0.5.1
#  flutter/services: ^2.0.0
#  flutter_webview_plugin: ^0.4.0
  flutter_animate: ^4.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/background/
    - assets/logo/
    - assets/lottie/
    - assets/icons/svg/
    - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
