class GetConfigValueResponse {
  int? responseCode;
  String? responseMessage;
  ResponseData? responseData;

  GetConfigValueResponse(
      {this.responseCode, this.responseMessage, this.responseData});

  GetConfigValueResponse.fromJson(Map<String, dynamic> json) {
    responseCode = json['responseCode'];
    responseMessage = json['responseMessage'];
    responseData = json['responseData'] != null
        ? new ResponseData.fromJson(json['responseData'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['responseCode'] = this.responseCode;
    data['responseMessage'] = this.responseMessage;
    if (this.responseData != null) {
      data['responseData'] = this.responseData!.toJson();
    }
    return data;
  }
}

class ResponseData {
  String? message;
  int? statusCode;
  Data? data;

  ResponseData({this.message, this.statusCode, this.data});

  ResponseData.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    statusCode = json['statusCode'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['statusCode'] = this.statusCode;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  String? dAILYLIMITCHECK;
  String? nATIVECURRENCYCODE;
  String? wEAKPASSWORDFIELDS;
  String? aNONWITHDRAWALLIMIT;
  String? dEFAULTDATETIMEFORMAT;
  String? cLIENTTOKENREGEX;
  String? wARNAME;
  String? aUTOPROCESSEDWITHDRAWALLIMIT;
  String? aCCOUNTOTPTYPE;
  String? aLLOCATIONMOBILEREGEX;
  String? oNEHOURWITHDRAWALALERTAMOUNT;
  String? pRIMARYIDTYPE;
  String? iNVALIDCHANGEPWDRETRYALLOWED;
  String? pASSWORDREGEX;
  String? fAILEDLOGINBLOCKUPDATETIME;
  String? gMTTIMEZONEDIFF;
  String? sCHEDULERUNBLOCKDURATION;
  String? sUSPICIOUSDEPOSITCOUNT;
  String? dRCORRECTIONPODMID;
  String? dEFAULTPROFIESTATUS;
  String? mONTHLYLIMITCHECK;
  String? jACKPOTCHUNKSIZE;
  String? nATIVECURRENCY;
  String? uSERMARKINACTIVEDAYS;
  String? cOUNTRYCODES;
  String? tELECOMMOBILEREGEXJSON;
  String? nOOFHISTORICALPASSWORD;
  String? tICKETREPRINTCOUNT;
  String? fAILEDCHANGEPWDBLOCKUPDATETIME;
  String? aCCOUNTOTPRESENDCOUNT;
  String? rEPORTCHUNKSIZE;
  String? fULLANDSEMIREGISTRATION;
  String? eMAILIMAGEPATH;
  String? fCMIOSTOPIC;
  String? sCHEDULERREPORTMAXSIZE;
  String? rEGULARWINNINGRETRYCOUNT;
  String? dEFAULTDATEFORMAT;
  String? eXTERNALCALLHEADERCREDENTIAL;
  String? cRCORRECTIONPODMID;
  String? wITHDRAWALBYOTP;
  String? eMAILVERIFICATIONONREGISTRATION;
  String? pASSWORDPOLICYID;
  String? fETCHACCOUNTSTATUS;
  String? dPPODMID;
  String? tOPPLAYERREPORTLIMIT;
  String? pRIMARYIDREGEX;
  String? gENOTPEXPIRY;
  String? pASSWORDLENGTH;
  String? dOMAINTIMEZONE;
  String? rGMERCHANTID;
  String? zIPCODEREGEX;
  String? wITHDRAWALOTPEXPIRY;
  String? bOUSERSYNCALLOWED;
  String? aMOUNTFORMATINGREQUIRED;
  String? sYSTEMPASSWORDHASHING;
  String? cOUNTRYCODE;
  String? rESETSECQUESDURATION;
  String? mPINEXPIRY;
  String? cURRENCYID;
  String? dEFAULTACCOUNTSTATUS;
  String? dATEFORMAT;
  String? rESCHEDULEALLOWED;
  String? dEFAULTPLAYERACCOUNTSTATUS;
  String? mOBILEVERIFICATIONLINK;
  String? aLLOWTXNONNOCRITERIA;
  String? oTPEXPIRY;
  String? bOUSERMARKTERMINATEDAYS;
  String? pHONEREGEX;
  String? mOBILEREGEX;
  String? dEFAULTKYCSTATUS;
  String? aDVANCEDREGISTRATIONREQUESTSTEPS;
  String? wITHDRAWALOTPRESENDCOUNT;
  String? rEPORTINGMERCHANTID;
  String? mAXACCOUNTLIMIT;
  String? sHOWKYCSTATUS;
  String? wEEKSTARTDAY;
  String? pLAYERTEXTVALUE;
  String? pASSWORDVALIDITYDAYS;
  String? dISPLAYCURRENCYSYMBOL;
  String? pAYMENTACCOUNTCHECKLEVEL;
  String? aVAILABLECURRENCIES;
  String? sUBSCRIPTIONMSGCOLOR;
  String? rMSSERVERURL;
  String? pLAYERDATASOURCE;
  String? eMAILVERIFICATIONLINKEXPIRY;
  String? nUMBERFORMATREQUIRED;
  String? eXPIREOLDDOCONREKYC;
  String? bOUSERMARKINACTIVEDAYS;
  String? pLRACCSTATUSMARKCLOSEDDAYS;
  String? pLAYERPAYMENTREDIRECTURL;
  String? rEPORTDATEDIFFERENCE;
  String? iSMAILMANDATORY;
  String? aUTOUSERREGISTER;
  String? aLLOWLOGINFOREXTERNALUSER;
  String? aCCOUNTOTPRETRYCOUNT;
  String? mULTIPROFILEUPDATELIMIT;
  String? mOBITELMESSAGESRETRYCOUNT;
  String? tPPODMID;
  String? pLAYERDOCUMENTEXPIRYREQUIRED;
  String? iCASHPLAYERSYNCRETRYCOUNT;
  String? sYSTEMSTIMEZONE;
  String? oPERATORWISEFILTER;
  String? rEPORTMAXSIZE;
  String? uPDATEUSERNAMEWITHMOBILE;
  String? pLAYERPASSWORDREGEX;
  String? dIALOGMESSAGESRETRYCOUNT;
  String? wITHDRAWALOTPRETRYCOUNT;
  String? rEPORTEMAILS;
  String? mERCHANTIPCHECK;
  String? cURRENCYLIST;
  String? mONTHSTARTDAY;
  String? bOSHUTDOWN;
  String? pAYMENTOPTION;
  String? pLAYERSECURITYQUESTIONREQUIRED;
  String? bULKMESSAGELIMIT;
  String? mAXFAILEDPODMTRANSACTIONCOUNT;
  String? aLLOWEDORGCODES;
  String? aCCOUNTOTPLENGTH;
  String? fCMANDROIDTOPIC;
  String? uPDATEUSERNAMEONMOBILEUPDATE;
  String? mULTIPLRACCSTATUSUPDATELIMIT;
  String? iPCHECKFORUSERTOKEN;
  String? rEGISTRATIONTYPE;
  String? mAXRECORDRETRIVELIMIT;
  String? pASSWORDTYPE;
  String? sECQUESVALIDATION;
  String? mULTIPLEACTIONALLOWEDBYSAMEUSER;
  String? uPDATEPROFILESTATUSWITHACCSTATUS;
  String? uIMOBILEREGEX;
  String? dGEMERCHANTID;
  String? rOUNDOFFREQUIRED;
  String? cLIENTNAME;
  String? wINTABLES;
  String? rESETSECQUESDURATIONSTATUS;
  String? dEFAULTDOMAIN;
  String? dEPOSITREQUERYCHECKTIME;
  String? cASHIERMERCHANTID;
  String? aLLOWEDDECIMALSIZE;
  String? tELECOMCONSENTREQUIRED;
  String? pLAYERMOBILENUMBERREQUIRED;
  String? tXNCHARGEMODE;
  String? wINNERDATAPUSHURL;
  String? cOMMBACKOFFICEURL;
  String? aLLOWEDUSERTYPES;
  String? sUBSCRIPTIONBGCOLOR;
  String? dEVELOPMODE;
  String? wEEKLYLIMITCHECK;
  String? uPDATEEMAILDURATION;
  String? sERVERIP;
  String? bONUSMERCHANTID;
  String? cRMSYNCALLOWED;
  String? uSERNAMEREGEX;
  String? aTMBATCHCAPACITY;
  String? iSBOGRACEPERIOD;
  String? hIGHWINNINGDEPOSIT;
  String? dUPLICATETRANSACTIONALLOWEDFREQUENCY;
  String? AnonymousToReg;

  Data(
      {this.dAILYLIMITCHECK,
        this.nATIVECURRENCYCODE,
        this.wEAKPASSWORDFIELDS,
        this.aNONWITHDRAWALLIMIT,
        this.dEFAULTDATETIMEFORMAT,
        this.cLIENTTOKENREGEX,
        this.wARNAME,
        this.aUTOPROCESSEDWITHDRAWALLIMIT,
        this.aCCOUNTOTPTYPE,
        this.aLLOCATIONMOBILEREGEX,
        this.oNEHOURWITHDRAWALALERTAMOUNT,
        this.pRIMARYIDTYPE,
        this.iNVALIDCHANGEPWDRETRYALLOWED,
        this.pASSWORDREGEX,
        this.fAILEDLOGINBLOCKUPDATETIME,
        this.gMTTIMEZONEDIFF,
        this.sCHEDULERUNBLOCKDURATION,
        this.sUSPICIOUSDEPOSITCOUNT,
        this.dRCORRECTIONPODMID,
        this.dEFAULTPROFIESTATUS,
        this.mONTHLYLIMITCHECK,
        this.jACKPOTCHUNKSIZE,
        this.nATIVECURRENCY,
        this.uSERMARKINACTIVEDAYS,
        this.cOUNTRYCODES,
        this.tELECOMMOBILEREGEXJSON,
        this.nOOFHISTORICALPASSWORD,
        this.tICKETREPRINTCOUNT,
        this.fAILEDCHANGEPWDBLOCKUPDATETIME,
        this.aCCOUNTOTPRESENDCOUNT,
        this.rEPORTCHUNKSIZE,
        this.fULLANDSEMIREGISTRATION,
        this.eMAILIMAGEPATH,
        this.fCMIOSTOPIC,
        this.sCHEDULERREPORTMAXSIZE,
        this.rEGULARWINNINGRETRYCOUNT,
        this.dEFAULTDATEFORMAT,
        this.eXTERNALCALLHEADERCREDENTIAL,
        this.cRCORRECTIONPODMID,
        this.wITHDRAWALBYOTP,
        this.eMAILVERIFICATIONONREGISTRATION,
        this.pASSWORDPOLICYID,
        this.fETCHACCOUNTSTATUS,
        this.dPPODMID,
        this.tOPPLAYERREPORTLIMIT,
        this.pRIMARYIDREGEX,
        this.gENOTPEXPIRY,
        this.pASSWORDLENGTH,
        this.dOMAINTIMEZONE,
        this.rGMERCHANTID,
        this.zIPCODEREGEX,
        this.wITHDRAWALOTPEXPIRY,
        this.bOUSERSYNCALLOWED,
        this.aMOUNTFORMATINGREQUIRED,
        this.sYSTEMPASSWORDHASHING,
        this.cOUNTRYCODE,
        this.rESETSECQUESDURATION,
        this.mPINEXPIRY,
        this.cURRENCYID,
        this.dEFAULTACCOUNTSTATUS,
        this.dATEFORMAT,
        this.rESCHEDULEALLOWED,
        this.dEFAULTPLAYERACCOUNTSTATUS,
        this.mOBILEVERIFICATIONLINK,
        this.aLLOWTXNONNOCRITERIA,
        this.oTPEXPIRY,
        this.bOUSERMARKTERMINATEDAYS,
        this.pHONEREGEX,
        this.mOBILEREGEX,
        this.dEFAULTKYCSTATUS,
        this.aDVANCEDREGISTRATIONREQUESTSTEPS,
        this.wITHDRAWALOTPRESENDCOUNT,
        this.rEPORTINGMERCHANTID,
        this.mAXACCOUNTLIMIT,
        this.sHOWKYCSTATUS,
        this.wEEKSTARTDAY,
        this.pLAYERTEXTVALUE,
        this.pASSWORDVALIDITYDAYS,
        this.dISPLAYCURRENCYSYMBOL,
        this.pAYMENTACCOUNTCHECKLEVEL,
        this.aVAILABLECURRENCIES,
        this.sUBSCRIPTIONMSGCOLOR,
        this.rMSSERVERURL,
        this.pLAYERDATASOURCE,
        this.eMAILVERIFICATIONLINKEXPIRY,
        this.nUMBERFORMATREQUIRED,
        this.eXPIREOLDDOCONREKYC,
        this.bOUSERMARKINACTIVEDAYS,
        this.pLRACCSTATUSMARKCLOSEDDAYS,
        this.pLAYERPAYMENTREDIRECTURL,
        this.rEPORTDATEDIFFERENCE,
        this.iSMAILMANDATORY,
        this.aUTOUSERREGISTER,
        this.aLLOWLOGINFOREXTERNALUSER,
        this.aCCOUNTOTPRETRYCOUNT,
        this.mULTIPROFILEUPDATELIMIT,
        this.mOBITELMESSAGESRETRYCOUNT,
        this.tPPODMID,
        this.pLAYERDOCUMENTEXPIRYREQUIRED,
        this.iCASHPLAYERSYNCRETRYCOUNT,
        this.sYSTEMSTIMEZONE,
        this.oPERATORWISEFILTER,
        this.rEPORTMAXSIZE,
        this.uPDATEUSERNAMEWITHMOBILE,
        this.pLAYERPASSWORDREGEX,
        this.dIALOGMESSAGESRETRYCOUNT,
        this.wITHDRAWALOTPRETRYCOUNT,
        this.rEPORTEMAILS,
        this.mERCHANTIPCHECK,
        this.cURRENCYLIST,
        this.mONTHSTARTDAY,
        this.bOSHUTDOWN,
        this.pAYMENTOPTION,
        this.pLAYERSECURITYQUESTIONREQUIRED,
        this.bULKMESSAGELIMIT,
        this.mAXFAILEDPODMTRANSACTIONCOUNT,
        this.aLLOWEDORGCODES,
        this.aCCOUNTOTPLENGTH,
        this.fCMANDROIDTOPIC,
        this.uPDATEUSERNAMEONMOBILEUPDATE,
        this.mULTIPLRACCSTATUSUPDATELIMIT,
        this.iPCHECKFORUSERTOKEN,
        this.rEGISTRATIONTYPE,
        this.mAXRECORDRETRIVELIMIT,
        this.pASSWORDTYPE,
        this.sECQUESVALIDATION,
        this.mULTIPLEACTIONALLOWEDBYSAMEUSER,
        this.uPDATEPROFILESTATUSWITHACCSTATUS,
        this.uIMOBILEREGEX,
        this.dGEMERCHANTID,
        this.rOUNDOFFREQUIRED,
        this.cLIENTNAME,
        this.wINTABLES,
        this.rESETSECQUESDURATIONSTATUS,
        this.dEFAULTDOMAIN,
        this.dEPOSITREQUERYCHECKTIME,
        this.cASHIERMERCHANTID,
        this.aLLOWEDDECIMALSIZE,
        this.tELECOMCONSENTREQUIRED,
        this.pLAYERMOBILENUMBERREQUIRED,
        this.tXNCHARGEMODE,
        this.wINNERDATAPUSHURL,
        this.cOMMBACKOFFICEURL,
        this.aLLOWEDUSERTYPES,
        this.sUBSCRIPTIONBGCOLOR,
        this.dEVELOPMODE,
        this.wEEKLYLIMITCHECK,
        this.uPDATEEMAILDURATION,
        this.sERVERIP,
        this.bONUSMERCHANTID,
        this.cRMSYNCALLOWED,
        this.uSERNAMEREGEX,
        this.aTMBATCHCAPACITY,
        this.iSBOGRACEPERIOD,
        this.hIGHWINNINGDEPOSIT,
        this.AnonymousToReg,
        this.dUPLICATETRANSACTIONALLOWEDFREQUENCY});

  Data.fromJson(Map<String, dynamic> json) {
    dAILYLIMITCHECK = json['DAILY_LIMIT_CHECK'];
    nATIVECURRENCYCODE = json['NATIVE_CURRENCY_CODE'];
    wEAKPASSWORDFIELDS = json['WEAK_PASSWORD_FIELDS'];
    aNONWITHDRAWALLIMIT = json['ANON_WITHDRAWAL_LIMIT'];
    dEFAULTDATETIMEFORMAT = json['DEFAULT_DATETIME_FORMAT'];
    cLIENTTOKENREGEX = json['CLIENT_TOKEN_REGEX'];
    wARNAME = json['WAR_NAME'];
    aUTOPROCESSEDWITHDRAWALLIMIT = json['AUTO_PROCESSED_WITHDRAWAL_LIMIT'];
    aCCOUNTOTPTYPE = json['ACCOUNT_OTP_TYPE'];
    aLLOCATIONMOBILEREGEX = json['ALLOCATION_MOBILE_REGEX'];
    oNEHOURWITHDRAWALALERTAMOUNT = json['ONE_HOUR_WITHDRAWAL_ALERT_AMOUNT'];
    pRIMARYIDTYPE = json['PRIMARY_ID_TYPE'];
    iNVALIDCHANGEPWDRETRYALLOWED = json['INVALID_CHANGE_PWD_RETRY_ALLOWED'];
    pASSWORDREGEX = json['PASSWORD_REGEX'];
    fAILEDLOGINBLOCKUPDATETIME = json['FAILED_LOGIN_BLOCK_UPDATE_TIME'];
    gMTTIMEZONEDIFF = json['GMT_TIME_ZONE_DIFF'];
    sCHEDULERUNBLOCKDURATION = json['SCHEDULER_UNBLOCK_DURATION'];
    sUSPICIOUSDEPOSITCOUNT = json['SUSPICIOUS_DEPOSIT_COUNT'];
    dRCORRECTIONPODMID = json['DR_CORRECTION_PODM_ID'];
    dEFAULTPROFIESTATUS = json['DEFAULT_PROFIE_STATUS'];
    mONTHLYLIMITCHECK = json['MONTHLY_LIMIT_CHECK'];
    jACKPOTCHUNKSIZE = json['JACKPOT_CHUNK_SIZE'];
    nATIVECURRENCY = json['NATIVE_CURRENCY'];
    uSERMARKINACTIVEDAYS = json['USER_MARK_INACTIVE_DAYS'];
    cOUNTRYCODES = json['COUNTRY_CODES'];
    tELECOMMOBILEREGEXJSON = json['TELECOM_MOBILE_REGEX_JSON'];
    nOOFHISTORICALPASSWORD = json['NO_OF_HISTORICAL_PASSWORD'];
    tICKETREPRINTCOUNT = json['TICKET_REPRINT_COUNT'];
    fAILEDCHANGEPWDBLOCKUPDATETIME =
    json['FAILED_CHANGE_PWD_BLOCK_UPDATE_TIME'];
    aCCOUNTOTPRESENDCOUNT = json['ACCOUNT_OTP_RESEND_COUNT'];
    rEPORTCHUNKSIZE = json['REPORT_CHUNK_SIZE'];
    fULLANDSEMIREGISTRATION = json['FULL_AND_SEMI_REGISTRATION'];
    eMAILIMAGEPATH = json['EMAIL_IMAGE_PATH'];
    fCMIOSTOPIC = json['FCM_IOS_TOPIC'];
    sCHEDULERREPORTMAXSIZE = json['SCHEDULER_REPORT_MAX_SIZE'];
    rEGULARWINNINGRETRYCOUNT = json['REGULAR_WINNING_RETRY_COUNT'];
    dEFAULTDATEFORMAT = json['DEFAULT_DATE_FORMAT'];
    eXTERNALCALLHEADERCREDENTIAL = json['EXTERNAL_CALL_HEADER_CREDENTIAL'];
    cRCORRECTIONPODMID = json['CR_CORRECTION_PODM_ID'];
    wITHDRAWALBYOTP = json['WITHDRAWAL_BY_OTP'];
    eMAILVERIFICATIONONREGISTRATION =
    json['EMAIL_VERIFICATION_ON_REGISTRATION'];
    pASSWORDPOLICYID = json['PASSWORD_POLICY_ID'];
    fETCHACCOUNTSTATUS = json['FETCH_ACCOUNT_STATUS'];
    dPPODMID = json['DP_PODM_ID'];
    tOPPLAYERREPORTLIMIT = json['TOP_PLAYER_REPORT_LIMIT'];
    pRIMARYIDREGEX = json['PRIMARY_ID_REGEX'];
    gENOTPEXPIRY = json['GEN_OTP_EXPIRY'];
    pASSWORDLENGTH = json['PASSWORD_LENGTH'];
    dOMAINTIMEZONE = json['DOMAIN_TIME_ZONE'];
    rGMERCHANTID = json['RG_MERCHANT_ID'];
    zIPCODEREGEX = json['ZIPCODE_REGEX'];
    wITHDRAWALOTPEXPIRY = json['WITHDRAWAL_OTP_EXPIRY'];
    bOUSERSYNCALLOWED = json['BO_USER_SYNC_ALLOWED'];
    aMOUNTFORMATINGREQUIRED = json['AMOUNT_FORMATING_REQUIRED'];
    sYSTEMPASSWORDHASHING = json['SYSTEM_PASSWORD_HASHING'];
    cOUNTRYCODE = json['COUNTRY_CODE'];
    rESETSECQUESDURATION = json['RESET_SEC_QUES_DURATION'];
    mPINEXPIRY = json['MPIN_EXPIRY'];
    cURRENCYID = json['CURRENCY_ID'];
    dEFAULTACCOUNTSTATUS = json['DEFAULT_ACCOUNT_STATUS'];
    dATEFORMAT = json['DATE_FORMAT'];
    rESCHEDULEALLOWED = json['RESCHEDULE_ALLOWED'];
    dEFAULTPLAYERACCOUNTSTATUS = json['DEFAULT_PLAYER_ACCOUNT_STATUS'];
    mOBILEVERIFICATIONLINK = json['MOBILE_VERIFICATION_LINK'];
    aLLOWTXNONNOCRITERIA = json['ALLOW_TXN_ON_NO_CRITERIA'];
    oTPEXPIRY = json['OTP_EXPIRY'];
    bOUSERMARKTERMINATEDAYS = json['BO_USER_MARK_TERMINATE_DAYS'];
    pHONEREGEX = json['PHONE_REGEX'];
    mOBILEREGEX = json['MOBILE_REGEX'];
    dEFAULTKYCSTATUS = json['DEFAULT_KYC_STATUS'];
    aDVANCEDREGISTRATIONREQUESTSTEPS =
    json['ADVANCED_REGISTRATION_REQUEST_STEPS'];
    wITHDRAWALOTPRESENDCOUNT = json['WITHDRAWAL_OTP_RESEND_COUNT'];
    rEPORTINGMERCHANTID = json['REPORTING_MERCHANT_ID'];
    mAXACCOUNTLIMIT = json['MAX_ACCOUNT_LIMIT'];
    sHOWKYCSTATUS = json['SHOW_KYC_STATUS'];
    wEEKSTARTDAY = json['WEEK_START_DAY'];
    pLAYERTEXTVALUE = json['PLAYER_TEXT_VALUE'];
    pASSWORDVALIDITYDAYS = json['PASSWORD_VALIDITY_DAYS'];
    dISPLAYCURRENCYSYMBOL = json['DISPLAY_CURRENCY_SYMBOL'];
    pAYMENTACCOUNTCHECKLEVEL = json['PAYMENT_ACCOUNT_CHECK_LEVEL'];
    aVAILABLECURRENCIES = json['AVAILABLE_CURRENCIES'];
    sUBSCRIPTIONMSGCOLOR = json['SUBSCRIPTION_MSG_COLOR'];
    rMSSERVERURL = json['RMS_SERVER_URL'];
    pLAYERDATASOURCE = json['PLAYER_DATA_SOURCE'];
    eMAILVERIFICATIONLINKEXPIRY = json['EMAIL_VERIFICATION_LINK_EXPIRY'];
    nUMBERFORMATREQUIRED = json['NUMBER_FORMAT_REQUIRED'];
    eXPIREOLDDOCONREKYC = json['EXPIRE_OLD_DOC_ON_REKYC'];
    bOUSERMARKINACTIVEDAYS = json['BO_USER_MARK_INACTIVE_DAYS'];
    pLRACCSTATUSMARKCLOSEDDAYS = json['PLR_ACC_STATUS_MARK_CLOSED_DAYS'];
    pLAYERPAYMENTREDIRECTURL = json['PLAYER_PAYMENT_REDIRECT_URL'];
    rEPORTDATEDIFFERENCE = json['REPORT_DATE_DIFFERENCE'];
    iSMAILMANDATORY = json['IS_MAIL_MANDATORY'];
    aUTOUSERREGISTER = json['AUTO_USER_REGISTER'];
    aLLOWLOGINFOREXTERNALUSER = json['ALLOW_LOGIN_FOR_EXTERNAL_USER'];
    aCCOUNTOTPRETRYCOUNT = json['ACCOUNT_OTP_RETRY_COUNT'];
    mULTIPROFILEUPDATELIMIT = json['MULTI_PROFILE_UPDATE_LIMIT'];
    mOBITELMESSAGESRETRYCOUNT = json['MOBITEL_MESSAGES_RETRY_COUNT'];
    tPPODMID = json['TP_PODM_ID'];
    pLAYERDOCUMENTEXPIRYREQUIRED = json['PLAYER_DOCUMENT_EXPIRY_REQUIRED'];
    iCASHPLAYERSYNCRETRYCOUNT = json['ICASH_PLAYER_SYNC_RETRY_COUNT'];
    sYSTEMSTIMEZONE = json['SYSTEMS_TIME_ZONE'];
    oPERATORWISEFILTER = json['OPERATOR_WISE_FILTER'];
    rEPORTMAXSIZE = json['REPORT_MAX_SIZE'];
    uPDATEUSERNAMEWITHMOBILE = json['UPDATE_USER_NAME_WITH_MOBILE'];
    pLAYERPASSWORDREGEX = json['PLAYER_PASSWORD_REGEX'];
    dIALOGMESSAGESRETRYCOUNT = json['DIALOG_MESSAGES_RETRY_COUNT'];
    wITHDRAWALOTPRETRYCOUNT = json['WITHDRAWAL_OTP_RETRY_COUNT'];
    rEPORTEMAILS = json['REPORT_EMAILS'];
    mERCHANTIPCHECK = json['MERCHANT_IP_CHECK'];
    cURRENCYLIST = json['CURRENCY_LIST'];
    mONTHSTARTDAY = json['MONTH_START_DAY'];
    bOSHUTDOWN = json['BO_SHUTDOWN'];
    pAYMENTOPTION = json['PAYMENT_OPTION'];
    pLAYERSECURITYQUESTIONREQUIRED = json['PLAYER_SECURITY_QUESTION_REQUIRED'];
    bULKMESSAGELIMIT = json['BULK_MESSAGE_LIMIT'];
    mAXFAILEDPODMTRANSACTIONCOUNT = json['MAX_FAILED_PODM_TRANSACTION_COUNT'];
    aLLOWEDORGCODES = json['ALLOWED_ORG_CODES'];
    aCCOUNTOTPLENGTH = json['ACCOUNT_OTP_LENGTH'];
    fCMANDROIDTOPIC = json['FCM_ANDROID_TOPIC'];
    uPDATEUSERNAMEONMOBILEUPDATE = json['UPDATE_USERNAME_ON_MOBILE_UPDATE'];
    mULTIPLRACCSTATUSUPDATELIMIT = json['MULTI_PLR_ACC_STATUS_UPDATE_LIMIT'];
    iPCHECKFORUSERTOKEN = json['IP_CHECK_FOR_USER_TOKEN'];
    rEGISTRATIONTYPE = json['REGISTRATION_TYPE'];
    mAXRECORDRETRIVELIMIT = json['MAX_RECORD_RETRIVE_LIMIT'];
    pASSWORDTYPE = json['PASSWORD_TYPE'];
    sECQUESVALIDATION = json['SEC_QUES_VALIDATION'];
    mULTIPLEACTIONALLOWEDBYSAMEUSER =
    json['MULTIPLE_ACTION_ALLOWED_BY_SAME_USER'];
    uPDATEPROFILESTATUSWITHACCSTATUS =
    json['UPDATE_PROFILE_STATUS_WITH_ACC_STATUS'];
    uIMOBILEREGEX = json['UI_MOBILE_REGEX'];
    dGEMERCHANTID = json['DGE_MERCHANT_ID'];
    rOUNDOFFREQUIRED = json['ROUND_OFF_REQUIRED'];
    cLIENTNAME = json['CLIENT_NAME'];
    wINTABLES = json['WIN_TABLES'];
    rESETSECQUESDURATIONSTATUS = json['RESET_SEC_QUES_DURATION_STATUS'];
    dEFAULTDOMAIN = json['DEFAULT_DOMAIN'];
    dEPOSITREQUERYCHECKTIME = json['DEPOSIT_REQUERY_CHECK_TIME'];
    cASHIERMERCHANTID = json['CASHIER_MERCHANT_ID'];
    aLLOWEDDECIMALSIZE = json['ALLOWED_DECIMAL_SIZE'];
    tELECOMCONSENTREQUIRED = json['TELECOM_CONSENT_REQUIRED'];
    pLAYERMOBILENUMBERREQUIRED = json['PLAYER_MOBILE_NUMBER_REQUIRED'];
    tXNCHARGEMODE = json['TXN_CHARGE_MODE'];
    wINNERDATAPUSHURL = json['WINNER_DATA_PUSH_URL'];
    cOMMBACKOFFICEURL = json['COMM_BACKOFFICE_URL'];
    aLLOWEDUSERTYPES = json['ALLOWED_USER_TYPES'];
    sUBSCRIPTIONBGCOLOR = json['SUBSCRIPTION_BG_COLOR'];
    dEVELOPMODE = json['DEVELOP_MODE'];
    wEEKLYLIMITCHECK = json['WEEKLY_LIMIT_CHECK'];
    uPDATEEMAILDURATION = json['UPDATE_EMAIL_DURATION'];
    sERVERIP = json['SERVER_IP'];
    bONUSMERCHANTID = json['BONUS_MERCHANT_ID'];
    cRMSYNCALLOWED = json['CRM_SYNC_ALLOWED'];
    uSERNAMEREGEX = json['USERNAME_REGEX'];
    aTMBATCHCAPACITY = json['ATM_BATCH_CAPACITY'];
    iSBOGRACEPERIOD = json['IS_BO_GRACE_PERIOD'];
    hIGHWINNINGDEPOSIT = json['HIGH_WINNING_DEPOSIT'];
    dUPLICATETRANSACTIONALLOWEDFREQUENCY = json['DUPLICATE_TRANSACTION_ALLOWED_FREQUENCY'];
    AnonymousToReg = json['ANONYMOUS_TO_REG'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['DAILY_LIMIT_CHECK'] = this.dAILYLIMITCHECK;
    data['NATIVE_CURRENCY_CODE'] = this.nATIVECURRENCYCODE;
    data['WEAK_PASSWORD_FIELDS'] = this.wEAKPASSWORDFIELDS;
    data['ANON_WITHDRAWAL_LIMIT'] = this.aNONWITHDRAWALLIMIT;
    data['DEFAULT_DATETIME_FORMAT'] = this.dEFAULTDATETIMEFORMAT;
    data['CLIENT_TOKEN_REGEX'] = this.cLIENTTOKENREGEX;
    data['WAR_NAME'] = this.wARNAME;
    data['AUTO_PROCESSED_WITHDRAWAL_LIMIT'] = this.aUTOPROCESSEDWITHDRAWALLIMIT;
    data['ACCOUNT_OTP_TYPE'] = this.aCCOUNTOTPTYPE;
    data['ALLOCATION_MOBILE_REGEX'] = this.aLLOCATIONMOBILEREGEX;
    data['ONE_HOUR_WITHDRAWAL_ALERT_AMOUNT'] = this.oNEHOURWITHDRAWALALERTAMOUNT;
    data['PRIMARY_ID_TYPE'] = this.pRIMARYIDTYPE;
    data['INVALID_CHANGE_PWD_RETRY_ALLOWED'] = this.iNVALIDCHANGEPWDRETRYALLOWED;
    data['PASSWORD_REGEX'] = this.pASSWORDREGEX;
    data['FAILED_LOGIN_BLOCK_UPDATE_TIME'] = this.fAILEDLOGINBLOCKUPDATETIME;
    data['GMT_TIME_ZONE_DIFF'] = this.gMTTIMEZONEDIFF;
    data['SCHEDULER_UNBLOCK_DURATION'] = this.sCHEDULERUNBLOCKDURATION;
    data['SUSPICIOUS_DEPOSIT_COUNT'] = this.sUSPICIOUSDEPOSITCOUNT;
    data['DR_CORRECTION_PODM_ID'] = this.dRCORRECTIONPODMID;
    data['DEFAULT_PROFIE_STATUS'] = this.dEFAULTPROFIESTATUS;
    data['MONTHLY_LIMIT_CHECK'] = this.mONTHLYLIMITCHECK;
    data['JACKPOT_CHUNK_SIZE'] = this.jACKPOTCHUNKSIZE;
    data['NATIVE_CURRENCY'] = this.nATIVECURRENCY;
    data['USER_MARK_INACTIVE_DAYS'] = this.uSERMARKINACTIVEDAYS;
    data['COUNTRY_CODES'] = this.cOUNTRYCODES;
    data['TELECOM_MOBILE_REGEX_JSON'] = this.tELECOMMOBILEREGEXJSON;
    data['NO_OF_HISTORICAL_PASSWORD'] = this.nOOFHISTORICALPASSWORD;
    data['TICKET_REPRINT_COUNT'] = this.tICKETREPRINTCOUNT;
    data['FAILED_CHANGE_PWD_BLOCK_UPDATE_TIME'] = this.fAILEDCHANGEPWDBLOCKUPDATETIME;
    data['ACCOUNT_OTP_RESEND_COUNT'] = this.aCCOUNTOTPRESENDCOUNT;
    data['REPORT_CHUNK_SIZE'] = this.rEPORTCHUNKSIZE;
    data['FULL_AND_SEMI_REGISTRATION'] = this.fULLANDSEMIREGISTRATION;
    data['EMAIL_IMAGE_PATH'] = this.eMAILIMAGEPATH;
    data['FCM_IOS_TOPIC'] = this.fCMIOSTOPIC;
    data['SCHEDULER_REPORT_MAX_SIZE'] = this.sCHEDULERREPORTMAXSIZE;
    data['REGULAR_WINNING_RETRY_COUNT'] = this.rEGULARWINNINGRETRYCOUNT;
    data['DEFAULT_DATE_FORMAT'] = this.dEFAULTDATEFORMAT;
    data['EXTERNAL_CALL_HEADER_CREDENTIAL'] = this.eXTERNALCALLHEADERCREDENTIAL;
    data['CR_CORRECTION_PODM_ID'] = this.cRCORRECTIONPODMID;
    data['WITHDRAWAL_BY_OTP'] = this.wITHDRAWALBYOTP;
    data['EMAIL_VERIFICATION_ON_REGISTRATION'] = this.eMAILVERIFICATIONONREGISTRATION;
    data['PASSWORD_POLICY_ID'] = this.pASSWORDPOLICYID;
    data['FETCH_ACCOUNT_STATUS'] = this.fETCHACCOUNTSTATUS;
    data['DP_PODM_ID'] = this.dPPODMID;
    data['TOP_PLAYER_REPORT_LIMIT'] = this.tOPPLAYERREPORTLIMIT;
    data['PRIMARY_ID_REGEX'] = this.pRIMARYIDREGEX;
    data['GEN_OTP_EXPIRY'] = this.gENOTPEXPIRY;
    data['PASSWORD_LENGTH'] = this.pASSWORDLENGTH;
    data['DOMAIN_TIME_ZONE'] = this.dOMAINTIMEZONE;
    data['RG_MERCHANT_ID'] = this.rGMERCHANTID;
    data['ZIPCODE_REGEX'] = this.zIPCODEREGEX;
    data['WITHDRAWAL_OTP_EXPIRY'] = this.wITHDRAWALOTPEXPIRY;
    data['BO_USER_SYNC_ALLOWED'] = this.bOUSERSYNCALLOWED;
    data['AMOUNT_FORMATING_REQUIRED'] = this.aMOUNTFORMATINGREQUIRED;
    data['SYSTEM_PASSWORD_HASHING'] = this.sYSTEMPASSWORDHASHING;
    data['COUNTRY_CODE'] = this.cOUNTRYCODE;
    data['RESET_SEC_QUES_DURATION'] = this.rESETSECQUESDURATION;
    data['MPIN_EXPIRY'] = this.mPINEXPIRY;
    data['CURRENCY_ID'] = this.cURRENCYID;
    data['DEFAULT_ACCOUNT_STATUS'] = this.dEFAULTACCOUNTSTATUS;
    data['DATE_FORMAT'] = this.dATEFORMAT;
    data['RESCHEDULE_ALLOWED'] = this.rESCHEDULEALLOWED;
    data['DEFAULT_PLAYER_ACCOUNT_STATUS'] = this.dEFAULTPLAYERACCOUNTSTATUS;
    data['MOBILE_VERIFICATION_LINK'] = this.mOBILEVERIFICATIONLINK;
    data['ALLOW_TXN_ON_NO_CRITERIA'] = this.aLLOWTXNONNOCRITERIA;
    data['OTP_EXPIRY'] = this.oTPEXPIRY;
    data['BO_USER_MARK_TERMINATE_DAYS'] = this.bOUSERMARKTERMINATEDAYS;
    data['PHONE_REGEX'] = this.pHONEREGEX;
    data['MOBILE_REGEX'] = this.mOBILEREGEX;
    data['DEFAULT_KYC_STATUS'] = this.dEFAULTKYCSTATUS;
    data['ADVANCED_REGISTRATION_REQUEST_STEPS'] =
        this.aDVANCEDREGISTRATIONREQUESTSTEPS;
    data['WITHDRAWAL_OTP_RESEND_COUNT'] = this.wITHDRAWALOTPRESENDCOUNT;
    data['REPORTING_MERCHANT_ID'] = this.rEPORTINGMERCHANTID;
    data['MAX_ACCOUNT_LIMIT'] = this.mAXACCOUNTLIMIT;
    data['SHOW_KYC_STATUS'] = this.sHOWKYCSTATUS;
    data['WEEK_START_DAY'] = this.wEEKSTARTDAY;
    data['PLAYER_TEXT_VALUE'] = this.pLAYERTEXTVALUE;
    data['PASSWORD_VALIDITY_DAYS'] = this.pASSWORDVALIDITYDAYS;
    data['DISPLAY_CURRENCY_SYMBOL'] = this.dISPLAYCURRENCYSYMBOL;
    data['PAYMENT_ACCOUNT_CHECK_LEVEL'] = this.pAYMENTACCOUNTCHECKLEVEL;
    data['AVAILABLE_CURRENCIES'] = this.aVAILABLECURRENCIES;
    data['SUBSCRIPTION_MSG_COLOR'] = this.sUBSCRIPTIONMSGCOLOR;
    data['RMS_SERVER_URL'] = this.rMSSERVERURL;
    data['PLAYER_DATA_SOURCE'] = this.pLAYERDATASOURCE;
    data['EMAIL_VERIFICATION_LINK_EXPIRY'] = this.eMAILVERIFICATIONLINKEXPIRY;
    data['NUMBER_FORMAT_REQUIRED'] = this.nUMBERFORMATREQUIRED;
    data['EXPIRE_OLD_DOC_ON_REKYC'] = this.eXPIREOLDDOCONREKYC;
    data['BO_USER_MARK_INACTIVE_DAYS'] = this.bOUSERMARKINACTIVEDAYS;
    data['PLR_ACC_STATUS_MARK_CLOSED_DAYS'] = this.pLRACCSTATUSMARKCLOSEDDAYS;
    data['PLAYER_PAYMENT_REDIRECT_URL'] = this.pLAYERPAYMENTREDIRECTURL;
    data['REPORT_DATE_DIFFERENCE'] = this.rEPORTDATEDIFFERENCE;
    data['IS_MAIL_MANDATORY'] = this.iSMAILMANDATORY;
    data['AUTO_USER_REGISTER'] = this.aUTOUSERREGISTER;
    data['ALLOW_LOGIN_FOR_EXTERNAL_USER'] = this.aLLOWLOGINFOREXTERNALUSER;
    data['ACCOUNT_OTP_RETRY_COUNT'] = this.aCCOUNTOTPRETRYCOUNT;
    data['MULTI_PROFILE_UPDATE_LIMIT'] = this.mULTIPROFILEUPDATELIMIT;
    data['MOBITEL_MESSAGES_RETRY_COUNT'] = this.mOBITELMESSAGESRETRYCOUNT;
    data['TP_PODM_ID'] = this.tPPODMID;
    data['PLAYER_DOCUMENT_EXPIRY_REQUIRED'] = this.pLAYERDOCUMENTEXPIRYREQUIRED;
    data['ICASH_PLAYER_SYNC_RETRY_COUNT'] = this.iCASHPLAYERSYNCRETRYCOUNT;
    data['SYSTEMS_TIME_ZONE'] = this.sYSTEMSTIMEZONE;
    data['OPERATOR_WISE_FILTER'] = this.oPERATORWISEFILTER;
    data['REPORT_MAX_SIZE'] = this.rEPORTMAXSIZE;
    data['UPDATE_USER_NAME_WITH_MOBILE'] = this.uPDATEUSERNAMEWITHMOBILE;
    data['PLAYER_PASSWORD_REGEX'] = this.pLAYERPASSWORDREGEX;
    data['DIALOG_MESSAGES_RETRY_COUNT'] = this.dIALOGMESSAGESRETRYCOUNT;
    data['WITHDRAWAL_OTP_RETRY_COUNT'] = this.wITHDRAWALOTPRETRYCOUNT;
    data['REPORT_EMAILS'] = this.rEPORTEMAILS;
    data['MERCHANT_IP_CHECK'] = this.mERCHANTIPCHECK;
    data['CURRENCY_LIST'] = this.cURRENCYLIST;
    data['MONTH_START_DAY'] = this.mONTHSTARTDAY;
    data['BO_SHUTDOWN'] = this.bOSHUTDOWN;
    data['PAYMENT_OPTION'] = this.pAYMENTOPTION;
    data['PLAYER_SECURITY_QUESTION_REQUIRED'] =
        this.pLAYERSECURITYQUESTIONREQUIRED;
    data['BULK_MESSAGE_LIMIT'] = this.bULKMESSAGELIMIT;
    data['MAX_FAILED_PODM_TRANSACTION_COUNT'] =
        this.mAXFAILEDPODMTRANSACTIONCOUNT;
    data['ALLOWED_ORG_CODES'] = this.aLLOWEDORGCODES;
    data['ACCOUNT_OTP_LENGTH'] = this.aCCOUNTOTPLENGTH;
    data['FCM_ANDROID_TOPIC'] = this.fCMANDROIDTOPIC;
    data['UPDATE_USERNAME_ON_MOBILE_UPDATE'] =
        this.uPDATEUSERNAMEONMOBILEUPDATE;
    data['MULTI_PLR_ACC_STATUS_UPDATE_LIMIT'] =
        this.mULTIPLRACCSTATUSUPDATELIMIT;
    data['IP_CHECK_FOR_USER_TOKEN'] = this.iPCHECKFORUSERTOKEN;
    data['REGISTRATION_TYPE'] = this.rEGISTRATIONTYPE;
    data['MAX_RECORD_RETRIVE_LIMIT'] = this.mAXRECORDRETRIVELIMIT;
    data['PASSWORD_TYPE'] = this.pASSWORDTYPE;
    data['SEC_QUES_VALIDATION'] = this.sECQUESVALIDATION;
    data['MULTIPLE_ACTION_ALLOWED_BY_SAME_USER'] =
        this.mULTIPLEACTIONALLOWEDBYSAMEUSER;
    data['UPDATE_PROFILE_STATUS_WITH_ACC_STATUS'] =
        this.uPDATEPROFILESTATUSWITHACCSTATUS;
    data['UI_MOBILE_REGEX'] = this.uIMOBILEREGEX;
    data['DGE_MERCHANT_ID'] = this.dGEMERCHANTID;
    data['ROUND_OFF_REQUIRED'] = this.rOUNDOFFREQUIRED;
    data['CLIENT_NAME'] = this.cLIENTNAME;
    data['WIN_TABLES'] = this.wINTABLES;
    data['RESET_SEC_QUES_DURATION_STATUS'] = this.rESETSECQUESDURATIONSTATUS;
    data['DEFAULT_DOMAIN'] = this.dEFAULTDOMAIN;
    data['DEPOSIT_REQUERY_CHECK_TIME'] = this.dEPOSITREQUERYCHECKTIME;
    data['CASHIER_MERCHANT_ID'] = this.cASHIERMERCHANTID;
    data['ALLOWED_DECIMAL_SIZE'] = this.aLLOWEDDECIMALSIZE;
    data['TELECOM_CONSENT_REQUIRED'] = this.tELECOMCONSENTREQUIRED;
    data['PLAYER_MOBILE_NUMBER_REQUIRED'] = this.pLAYERMOBILENUMBERREQUIRED;
    data['TXN_CHARGE_MODE'] = this.tXNCHARGEMODE;
    data['WINNER_DATA_PUSH_URL'] = this.wINNERDATAPUSHURL;
    data['COMM_BACKOFFICE_URL'] = this.cOMMBACKOFFICEURL;
    data['ALLOWED_USER_TYPES'] = this.aLLOWEDUSERTYPES;
    data['SUBSCRIPTION_BG_COLOR'] = this.sUBSCRIPTIONBGCOLOR;
    data['DEVELOP_MODE'] = this.dEVELOPMODE;
    data['WEEKLY_LIMIT_CHECK'] = this.wEEKLYLIMITCHECK;
    data['UPDATE_EMAIL_DURATION'] = this.uPDATEEMAILDURATION;
    data['SERVER_IP'] = this.sERVERIP;
    data['BONUS_MERCHANT_ID'] = this.bONUSMERCHANTID;
    data['CRM_SYNC_ALLOWED'] = this.cRMSYNCALLOWED;
    data['USERNAME_REGEX'] = this.uSERNAMEREGEX;
    data['ATM_BATCH_CAPACITY'] = this.aTMBATCHCAPACITY;
    data['IS_BO_GRACE_PERIOD'] = this.iSBOGRACEPERIOD;
    data['HIGH_WINNING_DEPOSIT'] = this.hIGHWINNINGDEPOSIT;
    data['DUPLICATE_TRANSACTION_ALLOWED_FREQUENCY'] = this.dUPLICATETRANSACTIONALLOWEDFREQUENCY;
    data['ANONYMOUS_TO_REG'] = this.AnonymousToReg;
    return data;
  }
}
